"""`torch` — the handful of names the compare scripts use.

Extracted from `value_diff.py` / `repack_verify.py`: two dtypes, three functions, and the
tensor methods those scripts call. A tensor's element type isn't tracked (torch's own
stubs don't either), so operations return `Tensor` and the numeric edges are `Any`.
"""

from typing import Any

class dtype:
    """A torch dtype object (`torch.float64`, …). Compared by identity, printed by `str`."""

    def __str__(self) -> str: ...

float64: dtype
float32: dtype
float16: dtype
bfloat16: dtype
int64: dtype
int32: dtype
int16: dtype
int8: dtype
uint8: dtype

class Size(tuple[int, ...]):
    """`Tensor.shape` — a tuple of dimensions."""

class Tensor:
    """Only the surface the scripts touch.

    `element_size()` is what `dump.py` reads for the stored width; `to()` casts (the
    scripts cast to float64 before comparing); `numpy()` hands the buffer to numpy;
    `reshape`/`view`/`contiguous` reshape without copying data.
    """

    dtype: dtype
    shape: Size
    def element_size(self) -> int: ...
    def numel(self) -> int: ...
    def nelement(self) -> int: ...
    def is_floating_point(self) -> bool: ...
    # `to` is overloaded in torch on dtype OR device ("cpu") OR another tensor; the
    # scripts use the first two, so the target stays `Any` rather than picking one.
    def to(self, target: Any, /, **kwargs: Any) -> Tensor: ...
    def numpy(self) -> Any: ...
    # torch takes the new shape either variadically or as one sequence; both are used.
    def reshape(self, *shape: Any) -> Tensor: ...
    def view(self, *shape: Any) -> Tensor: ...
    def contiguous(self) -> Tensor: ...
    def flatten(self) -> Tensor: ...
    def tolist(self) -> list[Any]: ...
    def item(self) -> Any: ...
    def cpu(self) -> Tensor: ...
    def detach(self) -> Tensor: ...
    # Reductions give back a 0-d Tensor, not a Python number — which is why the dunders
    # below exist: `float(sl.min())` and `bool(fin.all())` are how the scripts get out.
    def max(self) -> Tensor: ...
    def min(self) -> Tensor: ...
    def sum(self) -> Tensor: ...
    def mean(self) -> Tensor: ...
    def all(self) -> Tensor: ...
    def any(self) -> Tensor: ...
    def __getitem__(self, index: Any) -> Tensor: ...
    def __len__(self) -> int: ...
    def __sub__(self, other: Any) -> Tensor: ...
    def __abs__(self) -> Tensor: ...
    def __float__(self) -> float: ...
    def __int__(self) -> int: ...
    def __bool__(self) -> bool: ...

def frombuffer(buffer: Any, *, dtype: dtype, count: int = ..., offset: int = ...) -> Tensor: ...
def isfinite(input: Tensor, /) -> Tensor: ...
def masked_select(input: Tensor, mask: Tensor, /) -> Tensor: ...
def save(obj: Any, f: Any, /, **kwargs: Any) -> None: ...

__all__ = [
    "Size",
    "Tensor",
    "bfloat16",
    "dtype",
    "float16",
    "float32",
    "float64",
    "frombuffer",
    "int8",
    "int16",
    "int32",
    "int64",
    "isfinite",
    "masked_select",
    "save",
    "uint8",
]
